// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC8vyu2Fz3na5Q3wXeEiNYvMMuogjE20bE',
    appId: '1:717280964807:web:c3535b88847e7bcbb48ee2',
    messagingSenderId: '717280964807',
    projectId: 'mystic-primacy-455711-q3',
    authDomain: 'mystic-primacy-455711-q3.firebaseapp.com',
    storageBucket: 'mystic-primacy-455711-q3.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDwDzL_Rm0txF4-SsS7XL9nNcmAVuTCiz0',
    appId: '1:717280964807:android:dccb26f76d03fab6b48ee2',
    messagingSenderId: '717280964807',
    projectId: 'mystic-primacy-455711-q3',
    storageBucket: 'mystic-primacy-455711-q3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC9O7avqCrJtpG-6UsvzuLzhDlC4KkFLu8',
    appId: '1:717280964807:ios:746858be22ec84fab48ee2',
    messagingSenderId: '717280964807',
    projectId: 'mystic-primacy-455711-q3',
    storageBucket: 'mystic-primacy-455711-q3.firebasestorage.app',
    androidClientId: '717280964807-a8nn2mrc40rgror2k16vq245j1su9ill.apps.googleusercontent.com',
    iosClientId: '717280964807-tb0as8l7bun9n349gjftd6vdu7341ndi.apps.googleusercontent.com',
    iosBundleId: 'com.ai.vitty',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC9O7avqCrJtpG-6UsvzuLzhDlC4KkFLu8',
    appId: '1:717280964807:ios:746858be22ec84fab48ee2',
    messagingSenderId: '717280964807',
    projectId: 'mystic-primacy-455711-q3',
    storageBucket: 'mystic-primacy-455711-q3.firebasestorage.app',
    androidClientId: '717280964807-a8nn2mrc40rgror2k16vq245j1su9ill.apps.googleusercontent.com',
    iosClientId: '717280964807-tb0as8l7bun9n349gjftd6vdu7341ndi.apps.googleusercontent.com',
    iosBundleId: 'com.ai.vitty',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC8vyu2Fz3na5Q3wXeEiNYvMMuogjE20bE',
    appId: '1:717280964807:web:975582191e3d528cb48ee2',
    messagingSenderId: '717280964807',
    projectId: 'mystic-primacy-455711-q3',
    authDomain: 'mystic-primacy-455711-q3.firebaseapp.com',
    storageBucket: 'mystic-primacy-455711-q3.firebasestorage.app',
  );

}